// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnjkmbtgpadxspofsjaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5uamttYnRncGFkeHNwb2ZzamFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNTc4MjMsImV4cCI6MjA2NzYzMzgyM30.zmIPiTr1jYqp7z8UJhGc4agFYu6SVURPte9VCfGebx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});